edition = "2018"
version = "Two"
unstable_features = true
wrap_comments = true
combine_control_expr = false
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
format_strings = true
use_field_init_shorthand = true
format_code_in_doc_comments = true
max_width=79
