[font]
default = "Noto Sans"
monospace = "Fira Mono"

[color]
back = "#1c1b22" # background color
prim = "#883333" # primary color for accents
font = "#BABABA" # font color
fdim = "#444444" # dimmed font color
fbri = "#FFFFFF" # bright font color

[monitor]
name = "eDP1"
width = 1920
height = 1080

[alacritty]
font_size = 6.5

[i3status]

  [i3status.battery]
  enabled = true
  device = "BAT0"

  [i3status.backlight]
  enabled = true

  [i3status.velib]
  stations = []

[gsettings]
"org.cinnamon.desktop.default-applications.terminal" = { exec = "alacritty" }
