[alacritty]
font = "FiraMono Nerd Font"
font_size = 6.5

[i3status]

  [i3status.battery]
  enabled = true
  device = "BAT0"

  [i3status.backlight]
  enabled = true

  [i3status.velib]
  stations = []

[gsettings]

  [gsettings."org.cinnamon.desktop.default-applications.terminal"]
  exec = "alacritty"
