[user]
name = "Rémi Dupré"
email = "remi@dupre.io"
startup_lock = true
gdm_lock = false

[font]
default = "Noto Sans"
monospace = "Fira Mono"
awesome = "Font Awesome"

[color]
back = "#000000" # background color
prim = "#2e2f5d" # primary color for accents
font = "#BABABA" # font color
fdim = "#222222" # dimmed font color
fbri = "#FFFFFF" # bright font color

[monitor]
name = "eDP1"
width = 1920
height = 1080

[alacritty]
pixel_ratio = 1
font_size = 6.5

[i3status]

  [i3status.battery]
  enabled = true
  device = "BAT0"

  [i3status.backlight]
  enabled = true

  [i3status.velib]
  stations = []

  [i3status.gpu]
  enabled = false

  [[i3status.bluetooth]]
  label = "FP Earbuds"
  mac = "00:00:AB:CD:55:75"

  [[i3status.bluetooth]]
  label = "HyperX"
  mac = "04:21:44:49:4C:C6"

  [[i3status.bluetooth]]
  label = "Platan"
  mac = "5C:EB:68:70:9E:9E"

[gsettings."org.cinnamon.desktop.default-applications.terminal"]
exec = "alacritty"

[gsettings."org.gnome.desktop.interface"]
gtk-theme = "adw-gtk3-dark" # gtk <= 3.0
color-scheme = "prefer-dark" # gtk 4
icon-theme = "Numix"
font-name = "Noto Sans"
